import express from "express";
import fs from "fs";
import path from "path";
import { renderToStringAsync } from "preact-render-to-string";
import { h } from "preact";
import { build } from "esbuild";
import { Suspense, lazy } from 'preact/compat';
import { addRoute } from "./hooks";
import ejs from "ejs";
import { fileURLToPath } from "url";

/** @jsx h */

export function generateClientEntry(routesDir: string) {
  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const templateFile = path.join(__dirname, "./client.ts.ejs");
  const files = fs
    .readdirSync(routesDir)
    .filter(f => /\.(t|j)sx?$/.test(f))
    .filter(f => !f.startsWith("_")); // skip private/partials

  const code = ejs.render(
    fs.readFileSync(templateFile, "utf8"),
    {
      files,
      banner: "// 🪄 auto-generated by preact-kit"
    },
    { rmWhitespace: true }
  );

  fs.writeFileSync(path.join(routesDir, "_entry.tsx"), code);
  console.log("✨ generated src/_entry.tsx");
}

/**
 * createApp()
 * -----------
 * Boots an Express app, mounts API routes and SSR pages.
 * Also spawns esbuild in watch mode for client hydration bundle.
 */
export async function createApp() {
  const app = express();
  const cwd = process.cwd();
  const routesDir = path.join(cwd, "src");
  const apiDir = path.join(cwd, "api");
  const publicDir = path.join(cwd, "public");

  // 1️⃣ Serve static files
  if (fs.existsSync(publicDir)) {
    app.use(express.static(publicDir));
  }

  // 1.5️⃣ Generate client entry file
  generateClientEntry(path.join(process.cwd(), "src"));

  // 2️⃣ Build client bundle
  const clientEntry = path.join(cwd, "src/_entry.tsx");
  const outFile = path.join(publicDir, "index.js");

  await build({
    entryPoints: [clientEntry],
    outfile: outFile,
    bundle: true,
    sourcemap: true,
    jsx: "automatic",
    jsxImportSource: "preact",
    target: "es2020",
    loader: { ".tsx": "tsx", ".ts": "ts" },
    preserveSymlinks: true,
    alias: {
      preact: path.resolve(process.cwd(), "node_modules/preact"),
    },


  }).then(() => console.log("🧱 esbuild watching client bundle..."));

  // 3️⃣ Mount API routes
  console.log("Mounting API routes...");

  for (const file of fs.readdirSync(apiDir)) {
    if (!/\.(t|j)sx?$/.test(file)) {
      continue;
    }

    const route = "/" + file.replace(/\.(t|j)sx?$/, "");
    await import(path.join(apiDir, file)).then((mod) => {
      const handler = mod.default || mod.handler;
      if (typeof handler === "function") {
        console.log(`🔗 /api${route} -> ${path.join(apiDir, file)}`);
        app.use(`/api${route}`, handler);
        addRoute(`/api${route}`, handler);
      }
    });
  }

  // 4️⃣ SSR routes
  console.log("Mounting SSR routes...");

  for (const file of fs.readdirSync(routesDir)) {
    if (!/\.(t|j)sx?$/.test(file)) continue;

    const route = file === "index.tsx" ? "/" : "/" + file.replace(/\.(t|j)sx?$/, "");
    console.log(`🔗 ${route} -> ${path.join(routesDir, file)}`);

    // const mod = await import(path.join(routesDir, file));
    // const Component = mod.default;

    app.get(route, async (req, res, next) => {
      const Page = lazy(() => import(path.join(routesDir, file)));

      // const Page = lazy(async () => {
      //         // haha

      //         return { default: <Component /> }
      //       })

      const html = await renderToStringAsync(<Suspense fallback={<p>Loading</p>}><Page /></Suspense>);
      res.send(htmlWrapper(html));
      // } catch (err) {
      //   next(err);
      // }
    });
  }

  return app;
}

function htmlWrapper(body: string) {
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Preact-Kit</title>
  </head>
  <body>
    <div id="app">${body}</div>
    <script src="/index.js"></script>
    
  </body>
</html>`;
}